### ISSUE TITLE
accumulated size of entities is "50.000.001" that exceeded the "50.000.000" limit set by "FEATURE_SECURE_PROCESSING"

### ISSUE THREAD

**Issue by lmk-lmk** [pvoosten/explicit-semantic-analysis#2]
Hi, 
i am trying to run your esa implementation. However i get an error during indexing this wiki dump:
"enwiki-20170320-pages-articles-multistream.xml.bz2". This is a 13,7GB dump by the way.
 You can find them on this link:  [https://dumps.wikimedia.org/enwiki/20170320/](https://dumps.wikimedia.org/enwiki/20170320/)

The errors says:
> The accumulated size of entities is "50.000.001" that exceeded the "50.000.000" limit set by "FEATURE_SECURE_PROCESSING".

I wonder if you ran into the same problem and if you know how i can set the limit or disable them altogether. Thank you in advance.

```
Apr 18, 2017 1:02:12 PM be.vanoosten.esa.WikiIndexer parseXmlDump
SEVERE: null
org.xml.sax.SAXParseException; lineNumber: 64243259; columnNumber: 371; JAXP00010004: The accumulated size of entities is "50.000.001" that exceeded the "50.000.000" limit set by "FEATURE_SECURE_PROCESSING".
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.checkEntityLimit(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.handleCharacter(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEntityReference(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source)
	at javax.xml.parsers.SAXParser.parse(Unknown Source)
	at be.vanoosten.esa.WikiIndexer.parseXmlDump(WikiIndexer.java:95)
	at be.vanoosten.esa.Main.indexing(Main.java:227)
	at be.vanoosten.esa.Main.createEngIndex(Main.java:102)
	at be.vanoosten.esa.Main.main(Main.java:61)

```

**Comment by pvoosten** [comment]
Hi,

Thanks for trying my ESA implementation. From the stack trace, it seems that your problem is related to the SAX parser implementation. I found some possible solutions on [StackOverflow](http://stackoverflow.com/q/23952888/158702): try updating Xerces.

I know it takes a while to process multiple gigabytes of XML because everything runs sequentially. Therefore, the ability to play with different parameters is limited, especially for huge dumps like enwiki.

If there is enough interest and maybe a sponsor, I can look into creating a version that runs on a cluster and make it available for the world to experiment with. So spread the word...

Cheers,
Philip

**Comment by lmk-lmk** [comment]
Thank you for the suggestion.
But this solution works for me as well :
[Error: xml.sax.SAXParseException ](http://stackoverflow.com/questions/42991043/error-xml-sax-saxparseexception-while-parsing-a-xml-file-using-wikixmlj)

**Comment by pvoosten** [comment]
Great! Thanks for posting your solution.

**Comment by YipingNUS** [comment]
In case people face the same problem, Adding the following line to the code also solves the problem for me.

``` Java
System.setProperty("jdk.xml.totalEntitySizeLimit", String.valueOf(Integer.MAX_VALUE));
```
This is based on the following commit:

https://github.com/james-gould/mediawiki-tools-mwdumper/commit/e84d5a80908b4834a14fde7c8201bcd71457fa6d
